# Generated by Django 2.1.5 on 2019-01-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('codename', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='codename')),
            ],
            options={
                'swappable': 'FLEXIBLE_PLANS_FEATURE_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default', models.NullBooleanField(db_index=True, default=None, help_text='Both "Unknown" and "No" means that the plan is not default', unique=True)),
                ('available', models.BooleanField(db_index=True, default=False, help_text='Is still available for purchase', verbose_name='available')),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'swappable': 'FLEXIBLE_PLANS_PLAN_MODEL',
            },
        ),
        migrations.CreateModel(
            name='CumulativeFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('usage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('flexible_plans.feature',),
        ),
        migrations.CreateModel(
            name='MeteredFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('units', models.PositiveIntegerField(default=0)),
                ('usage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('flexible_plans.feature',),
        ),
        migrations.CreateModel(
            name='PermissionFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
            bases=('flexible_plans.feature',),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(to=settings.FLEXIBLE_PLANS_FEATURE_MODEL),
        ),
    ]
