# Generated by Django 2.2 on 2019-04-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('usage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('flexible_plans.feature',),
        ),
        migrations.CreateModel(
            name='MeteredFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('units', models.PositiveIntegerField(default=0)),
                ('usage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('flexible_plans.feature',),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Is visible in current offer', verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.FLEXIBLE_PLANS_CUSTOMER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.FLEXIBLE_PLANS_PLAN_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(through='flexible_plans.PlanFeature', to=settings.FLEXIBLE_PLANS_FEATURE_MODEL),
        ),
    ]
