# Generated by Django 2.2 on 2019-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0002_auto_20190417_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(choices=[('braintree', 'Braintree')], max_length=100),
        ),
    ]
