# Generated by Django 2.2.1 on 2019-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0004_auto_20190502_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
