# Generated by Django 2.2.1 on 2019-05-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flexible_plans', '0005_auto_20190510_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_flexible_plans.feature_set+', to='contenttypes.ContentType'),
        ),
    ]
