# Generated by Django 2.2.1 on 2019-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0007_permissionfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionfeature',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
