# Generated by Django 2.2.1 on 2019-05-13 14:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0008_auto_20190513_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expire',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_date',
            field=models.DateField(blank=True, help_text='The date when the subscription was canceled.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ended_at',
            field=models.DateField(blank=True, help_text='The date when the subscription ended.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, help_text='The starting date for the subscription.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=django_fsm.FSMField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('activating', 'Activating'), ('canceled', 'Canceled'), ('ended', 'Ended')], default='inactive', help_text='The state the subscription is in.', max_length=12, protected=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateField(blank=True, help_text='The date at which the trial ends. If set, overrides the computed trial end date from the plan.', null=True),
        ),
    ]
