# Generated by Django 2.2.1 on 2019-05-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0009_auto_20190513_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=django_fsm.FSMField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('activating', 'Activating'), ('canceled', 'Canceled'), ('ended', 'Ended')], default='inactive', help_text='The state the subscription is in.', max_length=12),
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('consumed_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.FLEXIBLE_PLANS_FEATURE_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.FLEXIBLE_PLANS_SUBSCRIPTION_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
