# Generated by Django 2.2.1 on 2019-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0010_auto_20190515_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('Braintree', 'Braintree')], max_length=100),
        ),
    ]
