# Generated by Django 2.2.2 on 2019-06-04 15:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_plans', '0011_auto_20190515_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
